application: metofficewatch
version: 1
runtime: python
api_version: 1

handlers:
- url: /css/(.*)\.less
  static_files: css/\1.less
  mime_type: text/css
  upload: css/(.*)\.less

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js/(.*)\.coffee
  static_files: js/\1.coffee
  mime_type: text/coffeescript
  upload: js/(.*)\.coffee

- url: /js
  static_dir: js

- url: /(.*)\.(html|txt)
  static_files: statics/\1.\2 
  upload: statics/(.*)

- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

- url: /admin(/.*)?
  script: admin/main.py
  login: admin

- url: .*
  script: main.py


builtins:
- datastore_admin: on
- remote_api: on